---
# Install Docker compose
#
# Sample commands from https://github.com/docker/compose/releases
#   curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose
#   chmod +x /usr/local/bin/docker-compose

# Look for the shared_folder variable for Vagrant-based installs
- name: Look for previously downloaded file
  stat: path=/home/vagrant/shared/installers/
  register: shared_folder

- name: Check for already downloaded file, if a shared directory exists
  stat:
    path: "/home/vagrant/shared/installers/{{ role_name }}-role/docker-compose-{{ docker_compose_version }}"
  register: shared_file
  when: shared_folder.stat.exists

- name: Download Docker compose to shared folder if not present
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: "/home/vagrant/shared/installers/{{ role_name }}-role/docker-compose-{{ docker_compose_version }}"
    mode: "u+x,g+x,o+x"
  when: shared_folder.stat.exists and not shared_file.stat.exists

# gotcha: if file fails to download to shared folder, this step will error
- name: Copy docker-compose from shared folder
  command: "cp /home/vagrant/shared/installers/{{ role_name }}-role/docker-compose-{{ docker_compose_version }} /usr/local/bin/docker-compose"
  when: shared_folder.stat.exists

- name: Install Docker compose when no shared folder
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: "u+x,g+x,o+x"
  when: not shared_folder.stat.exists